---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: query-executor
parameters:
- name: DB_SECRET_NAME
  value: "assisted-installer-rds"
- name: SQL_EXECUTE_IMAGE
  value: quay.io/fedora/postgresql-15
- name: SQL_EXECUTE_TAG
  value: "15"
- name: SQL_EXECUTE_MEMORY_REQUEST
  value: 256Mi
- name: SQL_EXECUTE_MEMORY_LIMIT
  value: 256Mi
- name: SQL_EXECUTE_CPU_REQUEST
  value: "1"
- name: SQL_EXECUTE_CPU_LIMIT
  value: "1"
- name: SQL_EXECUTE_IMAGE_PULL_POLICY
  value: Always
- name: QUERY
  required: true
  value: ''
- name: QUERY_ID
  required: true
  value: ''
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: assisted-query-${QUERY_ID}
  spec:
    template:
      spec:
        volumes:
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0755
        restartPolicy: Never
        containers:
        - name: psql-execute-query
          image: ${SQL_EXECUTE_IMAGE}:${SQL_EXECUTE_TAG}
          imagePullPolicy: ${SQL_EXECUTE_IMAGE_PULL_POLICY}
          command:
          - /entrypoint.sh
          resources:
            limits:
              memory: ${SQL_EXECUTE_MEMORY_LIMIT}
              cpu: ${SQL_EXECUTE_CPU_LIMIT}
            requests:
              memory: ${SQL_EXECUTE_MEMORY_REQUEST}
              cpu: ${SQL_EXECUTE_CPU_REQUEST}
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: db.host
                name: ${DB_SECRET_NAME}
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: db.name
                name: ${DB_SECRET_NAME}
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: db.password
                name: ${DB_SECRET_NAME}
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: db.port
                name: ${DB_SECRET_NAME}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: ${DB_SECRET_NAME}
          volumeMounts:
          - name: scripts
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: scripts
  data:
    entrypoint.sh: |
      #!/bin/sh
      PGPASSWORD=$DB_PASS psql -e -a -U $DB_USER -d $DB_NAME -h $DB_HOST -p $DB_PORT -c "${QUERY}"
